name: xml_parser
description: >-
  An unopinionated XML parser that can
  read, traverse, and write XML documents.
version: 0.1.0
author: James Alexander <j.alex@email.com>
homepage: https://github.com/james-alex/xml_parser

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  html_character_entities: ^0.1.2
  http: ^0.12.0+2
  recursive_regex: ^0.1.3
  meta: ^1.1.7

dev_dependencies:
  test: ^1.6.5
